### PR TITLE
Dallas temp sensor fix?

### PR DESCRIPTION
**Pull request by spiff72**
Hello,

I have been posting several comments about my attempts to fix the issue with my pi reporting a CPU temp of 0 in the issue thread that you closed out a few days ago.  I have been playing around here (trying to learn pycharm, and also trying to figure out github), and I THINK that I have created a branch here that fixes the issue (at least for me).  Creating this as a pull request (to the best of my ability) for you to look at as a fix in the future.

Again, I am very new to coding, and just managed to piece something together that works for me (and to the best of my knowledge, only for me), but I don't think that it should do anything harmful.

I didn't attempt to update any version numbers in this, as I don't know the correct procedure for doing so.

Thanks!

### CODE REVIEW

**Comment by Stone-Hedge** [comment]
Tested & working on my pi Pi4 build with Dallas enclosure sensor.

**Comment by spiff72** [comment]
Thanks for confirming, @Stone-Hedge !

**Comment by StefanCohen** [comment]
Thanks for the PR. I will try it out and most likely merge it.

**Comment by StefanCohen** [comment]
Ok. Merged. Just please be careful with line breaks. They cause a lot of hassles when reviewing PRs. Thanks!

**Comment by spiff72** [comment]
Can you elaborate on what you mean about being careful with the line breaks?  (Just so I know what to look out for in the future...)
Thanks!

**Comment by StefanCohen** [comment]
Your editor is probably configured to remove trailing spaces, change line break type from cr to crlf, change tabs chars to space chars, etc. This causes "cosmetic" implicit changes in the diff file on lines that you don't intend to change functionally and thus makes it harder to review what you actually intend to update with the PR. Don't get me wrong. It doesn't break anything. It just makes it harder to review as one manually needs to review all the changed lines even if the change doesn't do anything.

**Comment by spiff72** [comment]
OK - that makes sense.  I did make some adjustments to the import statements at the top of the file that I changed at one point and then removed them, so that likely changed a few things too.  I will keep this in mind for the next project :-)

**Pull request merged**
