### PR TITLE
Support for Multicam with off toggle

### PR DESCRIPTION
**Pull request by CynanX**
An Off and Cam 1 button has been added above the webcam stream, provided 'Show webcam' is enabled.

If the Mutlicam plugin is install a button for each of these cameras will be shown instead.

### CODE REVIEW

**Comment by CynanX** [comment]
Current the buttons for the cameras as display top to bottom. I would like to make these show horizontally, and as smaller icons. However I'm not sure how to do this.. I attempted some CSS but it did not work properly. The webcam controls will still show when Octoprints Enable Webcam is disabled, however this is existing and I believe should be fixed in a separate, smaller commit.

**Comment by StefanCohen** [comment]
Thanks. I'm currently on vacation but will review after the weekend .

**Comment by CynanX** [comment]
Webcam toggle now shows as an icon next to the full screen buttons. I took the icon from the same place the others are from and I think it looks alright.

The webcam stream toggles now float on top of the stream on the top-right as text (Cam 2, Cam 1, Cam 0 etc).

Seems to work in full browser and full screen mode from what I can tell. I still don't know how to test Touch UI.

I would like to change the webcam stream buttons to smaller icons with numbers in but the icon resource website did not have any I could find that would be suitable. Perhaps use a custom font for it? Not sure.

**Comment by CynanX** [comment]
Buttons changed to use the webcam icon. The icons will show faded but highlight when the mouse if hovered over them.

**Comment by StefanCohen** [comment]
I just wanted to let you know that I haven't forgotten about this but I have a ton of other things to work on at the moment so the review will have to wait a bit. Thanks for your patience.

**Comment by StefanCohen** [comment]
Ok. I have reviewed it now and I think it looks really good. I'm not sure how the multicam plugin handles camera rotation/flipping but that's a different story. The only two issues I have found so far are:

* The overlaid icon buttons for each camera doesn't show over a dark (black) background. This can happen if the aspect ratio is for example 4:3 and "use theme colors in fullscreen mode is unchecked." This can easily be fixed in css.
* The camera icon overlay icons probably should have a tooltip with the camera name. The tooltip is currently "Switch camera stream". At leas with only two streams configured.
* The camera buttons seems out of order compared to the order they are configured in the multicam plugin.


Anyway. Good work! I intend to keep this merged in origin/master for the next release so please re-base and provide additional PRs if you want to.

//Stefan

**Comment by CynanX** [comment]
Thank you for your kind words!

MultiCam uses the main cameras rotation settings at the moment. I figured once that’s updated we can then update the dashboard bit.

- Yeah need to tie the colours into themes. Something to investigate.

- Good idea. I should be able to do that.

- I need to work out how to reverse the for loop for that one.

I’d like to find some way of doing numbers for the camera icons too if that’s possible.

I’ll do a new PR for changes if I can figure it out :)

**Comment by StefanCohen** [comment]
Yeah. Numbers for the cam icons will probably be tricky but I think a tooltip will be enough. At least for people not using touch screens.

I'm currently trying to solve a few bugs and add support for snmp sensors (via a new command line widget type).

**Pull request merged**
