### PR TITLE
minor style enhancements

### PR DESCRIPTION
**Pull request by Klammerson**
I simply added some css class ids to the elements so you can be able to change the css in themeify dedicated to each element or group

I also corrected the dasboard to dashboard

### CODE REVIEW

**Comment by Klammerson** [comment]
I'd also recommend that you remove all styles within the HTML code and put it into the css since it sometimes overrides the custom styles

**Comment by Klammerson** [comment]
and I have another pull request but maybe we chat before since this is just a version of my style idea. nothing major

**Comment by StefanCohen** [comment]
Thanks for the PR. I will review it.

There is at least one other plugin I will need to notify about the corrected typo since it currently depends on it be in misspelled. I also beleive there was a problem in some browsers with svg styling that prevented me from having it in the css so I was forced to put it inline but that should be easy to check. What browsers have you tested the PR against?

**Comment by Klammerson** [comment]
so far i checked safari and chrome

**Comment by StefanCohen** [comment]
Cool. I will check FF.

**Comment by StefanCohen** [comment]
Ok. I have tried it but the PR broke multiple things. I'm honestly not sure but I think it is because you have have missed to include the required changes in dashboard.js since both full browser and full screen modes are broken after the merge. The widgets are also rendered wrong. Did you happen to miss a few files when creating the PR?

**Comment by Klammerson** [comment]
ok this is strange since I tested my changes locally. but this doesn't mean that I am right about it.
maybe I need to check some more things. sorry for that

**Pull request merged**
